services:
  devel-app:
    build: .
    ports:
      - "8565:8565"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - NEXT_PUBLIC_DAREDEVIL_API_URL=${NEXT_PUBLIC_DAREDEVIL_API_URL}
    restart: unless-stopped
    container_name: devel-app
